### ISSUE TITLE
org-rainbow-tags--get-face: Symbol’s value as variable is void: color

### ISSUE THREAD

**Issue by lytex** [KaratasFurkan/org-rainbow-tags#1]
I don't understand how this plugin works...

Is color supposed to be a symbol? I can only get the plugin to work if I set a specific color in the configuration: `:foreground "red"` , `:foreground "orange"`, ... but `:foreground color` returns the error of the title and `:foreground 'color`  returns also an error: "org-rainbow-tags--get-face: Wrong type argument: stringp, color"

I'm using emacs 28.2 with doom 3.0.0

**Comment by KaratasFurkan** [comment]
Hello, first of all, you don't need to set `org-rainbow-tags-face-attributes` to make it work. It has a default value.

If you wanna change the face, you can set it like `(setq org-rainbow-tags-face-attributes '(:foreground color :underline t))`.

> Is color supposed to be a symbol?

It's kinda hacky. It's used in a macro and it needs to be used as just `color` e.g. `:foreground color`. The `color` is replaced with the auto-generated color in some part of the code.

If these doesn't help, can you share how do you try to set it up?

**Comment by tdstoff** [comment]
I use the `use-package` declaration without any customizations and I also get the error mentioned here. Is `color` not initialized without the customize statement?

```
(use-package org-rainbow-tags
  :straight (:host github :repo "KaratasFurkan/org-rainbow-tags")
  :hook (org-mode . org-rainbow-tags-mode))
```

**Comment by KaratasFurkan** [comment]
It must be a version problem, I'm on a random commit of 28.0.50 and the same snippet works for me. I guess I need to remove the `color` hack. I'll make the update soon :+1:

**Comment by KaratasFurkan** [comment]
I pushed a fix, can you try again?

Don't forget to run `straight-pull-package` and `straight-rebuild-package` if you use `straight.el`.

**Comment by lytex** [comment]
Great! It's working now

**Comment by KaratasFurkan** [comment]
Let's wait a few days until @tdstoff confirms it too before closing this issue.

**Comment by tdstoff** [comment]
Yes, worked for me as well. Thank you!
