### ISSUE TITLE
Indented properties get colored

### ISSUE THREAD

**Issue by gopar** [KaratasFurkan/org-rainbow-tags#3]
Looks like properties get colored if they indented (I know this is technically a "bug" but I really like the coloring of properties lol)

![Screen Shot 2022-11-13 at 8 46 54 AM](https://user-images.githubusercontent.com/1545083/201527844-0ed2156a-c8f3-4f8c-9510-1404284e5e7f.png)
![Screen Shot 2022-11-13 at 8 47 49 AM](https://user-images.githubusercontent.com/1545083/201527898-8f72bc81-92e2-4968-8a41-de4b9392ff07.png)

**Comment by KaratasFurkan** [comment]
> I really like the coloring of properties lol

We may say it's a feature then :grin: 

Joking aside, I know that anything between colons (`:`) are get colored. I've managed to prevent it for colons that is the first character of the line. It at least prevents non-indented properties, but of course [the regexp should be improved](https://github.com/KaratasFurkan/org-rainbow-tags/issues/2).
However, I'm not good at regexp unfortunately, it would be awesome if a regexp expert come and fix it :slightly_smiling_face: I'll try to fix it in my free times too.

**Comment by gopar** [comment]
I think org mode does provide some internal parsing api in order to know if someone is a tag or properties (although I've heard that it can get complicated due to how the code is structured). Sadly I'm no org mode or regex expert. Regardless I don't think this is a huge deal if it doesn't get fixed. (unless a lot of people complain lol)

**Comment by edgar-vincent** [comment]
From the little experience I have of it, [org-ml](https://github.com/ndwarshuis/org-ml), which is a "frontend" to Org's API, is very easy to use. It would probably be a lot sturdier than a regexp.

Colors on properties are nice, but I don't think they should be enabled by default, as this behaviour is not expected.

**Comment by wigingtont2** [comment]
I came up with this:

```
(defun org-rainbow-tags--apply-overlays ()
  "Add the auto-generated tag faces."
  (org-rainbow-tags--delete-overlays)
  (save-excursion
    (goto-char (point-min))
    (while (re-search-forward org-tag-line-re nil t)
      (save-excursion
        (goto-char (match-beginning 0))
        (while (re-search-forward org-rainbow-tags--org-tag-regexp (line-end-position) t)
          (let* ((overlay (make-overlay (match-beginning 1) (match-end 1))))
            (overlay-put overlay 'face (org-rainbow-tags--get-face 1))
            (add-to-list 'org-rainbow-tags--overlays overlay)))))))
```

This will still incorrectly color anything other than tags in a headline surrounded by colons though. I based this on looking at org--get-local-tags and org-get-tags. org-get-tags only grabs the actual tags, but I haven't figured out how.

**Comment by wigingtont2** [comment]
I tweaked it some more, and this seems to work for all cases I can think of:

```
(defun org-rainbow-tags--apply-overlays ()
  "Add the auto-generated tag faces."
  (org-rainbow-tags--delete-overlays)
  (save-excursion
    (goto-char (point-min))
    (while (re-search-forward org-outline-regexp nil t)
      (save-excursion
        (re-search-forward org-tag-group-re nil t)
        (goto-char (match-beginning 0))
        (while (re-search-forward org-rainbow-tags--org-tag-regexp (line-end-position) t)
          (let* ((overlay (make-overlay (match-beginning 1) (match-end 1))))
            (overlay-put overlay 'face (org-rainbow-tags--get-face 1))
            (add-to-list 'org-rainbow-tags--overlays overlay)
            (backward-char 2)))))))
```

**Comment by wigingtont2** [comment]
The last version would hang the UI for a second or two on my largest org file (~10K lines). I think that was org-outline-regexp hitting a lot of matches that didn't matter for this, so I went back to org-tag-line-re.

```
(defun org-rainbow-tags--apply-overlays ()
  "Add the auto-generated tag faces."
  (org-rainbow-tags--delete-overlays)
  (save-excursion
    (goto-char (point-min))
    (while (re-search-forward org-tag-line-re nil t)
      (goto-char (match-beginning 0))
      (while (re-search-forward org-tag-group-re (line-end-position) t)
        (when (eolp)
          (save-excursion
            (goto-char (match-beginning 0))
            (while (re-search-forward org-rainbow-tags--org-tag-regexp (line-end-position) t)
              (let* ((overlay (make-overlay (match-beginning 1) (match-end 1))))
                (overlay-put overlay 'face (org-rainbow-tags--get-face 1))
                (add-to-list 'org-rainbow-tags--overlays overlay)
                (backward-char 2)))))))))
```

**Comment by dchrzanowski** [comment]
What about just having a list of ignored tags? I know it's a bit hacky but you could include in the ignored list the PROPERTIES word and anything else that you don't want colored.

**Comment by KaratasFurkan** [comment]
Apologies for the late response.

@dchrzanowski that's a good suggestion. However, that list might be impossible to complete. For example, I use org mode as a rest api client and sometimes responses includes numbers like `5315:352:6316136:` and these are getting colored. Since these are random numbers, it's inevitable.

@wigingtont2 thanks for the contribution. Your last code block seems to work. Would you like to create a PR?

**Comment by wigingtont2** [comment]
@KaratasFurkan I can look at getting a PR ready in the next few days. I haven't done PRs on GitHub before though. Just in case I don't get around to it, I have provided my most recent local copy below. I started using filetags, and those were not getting colored.

```
(defvar org-filetags-regexp
  (rx (seq
       line-start
       "#+filetags:"
       (one-or-more whitespace)
       ;; Capture the rest of the line
       (group-n 1 (zero-or-more any))))
  "Regular expression to match Org-mode filetags lines.")

(defun org-rainbow-tags--apply-overlay-to-matched-line ()
  ""
  (goto-char (match-beginning 0))
  (while (re-search-forward org-tag-group-re (line-end-position) t)
    (when (eolp)
      (save-excursion
        (goto-char (match-beginning 0))
        (while (re-search-forward org-rainbow-tags--org-tag-regexp (line-end-position) t)
          (let* ((overlay (make-overlay (match-beginning 1) (match-end 1))))
            (overlay-put overlay 'face (org-rainbow-tags--get-face 1))
            (add-to-list 'org-rainbow-tags--overlays overlay)
            (backward-char 2)))))))

(defun org-rainbow-tags--apply-overlays ()
  "Add the auto-generated tag faces."
  (org-rainbow-tags--delete-overlays)
  (save-excursion
    (goto-char (point-min))
    (when (re-search-forward
           org-filetags-regexp
           (save-excursion (org-next-visible-heading 1) (beginning-of-line) (point)) t)
      (org-rainbow-tags--apply-overlay-to-matched-line))
    (while (re-search-forward org-tag-line-re nil t)
      (org-rainbow-tags--apply-overlay-to-matched-line))))
```

**Comment by KaratasFurkan** [comment]
Thank you. No need to rush, feel free to take your time.

**Comment by KaratasFurkan** [comment]
Fixed in https://github.com/KaratasFurkan/org-rainbow-tags/pull/4 thanks to @wigingtont2 :tada:
